# Project: DziennikOcen
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "source\ files/main.o" "source\ files/Subject.o" "source\ files/Utils.o"
LINKOBJ  = "source files/main.o" "source files/Subject.o" "source files/Utils.o"
LIBS     = -L"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/lib" -L"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/kmusialski/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DziennikOcen.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"source\ files/main.o": source\ files/main.cpp
	$(CPP) -c "source files/main.cpp" -o "source files/main.o" $(CXXFLAGS)

"source\ files/Subject.o": source\ files/Subject.cpp
	$(CPP) -c "source files/Subject.cpp" -o "source files/Subject.o" $(CXXFLAGS)

"source\ files/Utils.o": source\ files/Utils.cpp
	$(CPP) -c "source files/Utils.cpp" -o "source files/Utils.o" $(CXXFLAGS)
